version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "54355:5432"
  rails-app:
    build: ./rails-app
    volumes:
      - ./rails-app:/rails-app
      - ./rails-app/node_modules:/rails-app/node_modules
    ports:
      - "3010:3000"
    depends_on:
      - db
